# Generated by Django 5.0.6 on 2025-11-16 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_coupon_utilisation_par_utilisateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='users_used',
            field=models.ManyToManyField(blank=True, related_name='coupons_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
