# Generated by Django 5.0.6 on 2025-12-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0004_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='name_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
