# Generated by Django 5.0.6 on 2025-12-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0005_photobooth_description_en_photobooth_description_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobooth',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='description_nl',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='name_nl',
        ),
    ]
