# Generated by Django 5.0.6 on 2025-12-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0006_remove_photobooth_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='photobooths.accessory'),
        ),
    ]
