# Generated by Django 5.2.7 on 2026-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_accessory_photobooth_accessory_active_and_more'),
        ('photobooths', '0007_accessory_description_accessory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobooth',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='admin_panel.accessory'),
        ),
    ]
