# Generated by Django 5.2.7 on 2026-05-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0008_alter_photobooth_accessories'),
        ('reservations', '0008_remove_reservation_accessories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='accessories',
        ),
    ]
