# Generated by Django 5.2.7 on 2026-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0009_delete_accessory_remove_photobooth_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
