# Generated by Django 5.2.7 on 2026-06-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0010_photobooth_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobooth',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='description_nl',
            field=models.TextField(null=True),
        ),
    ]
