# Generated by Django 5.0.6 on 2025-12-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_invoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='accessories',
        ),
    ]
