# Generated by Django 5.0.6 on 2025-12-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0006_remove_photobooth_description_en_and_more'),
        ('reservations', '0004_remove_reservation_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='photobooths.accessory'),
        ),
    ]
