# Generated by Django 5.0.6 on 2025-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_paid',
            field=models.BooleanField(default=False),
        ),
    ]
