# Generated by Django 5.2.7 on 2026-05-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_invoice_coupon_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='accessories',
        ),
    ]
