# Generated by Django 5.2.7 on 2026-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='heure_livraison',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
