# Generated by Django 5.2.7 on 2026-04-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_account_type_customuser_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('user', 'Particulier'), ('company', 'Entreprise')], default='user', max_length=20),
        ),
    ]
