# Generated by Django 5.2.7 on 2026-05-25 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('duree', models.PositiveIntegerField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée')], default='unpaid', max_length=20)),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='accounts.devis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
