# Generated by Django 5.2.7 on 2026-06-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='duree',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
