# Generated by Django 5.2.7 on 2026-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_devis_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
