# Generated by Django 5.2.7 on 2026-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_devis_client_address_devis_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='client_vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
