# Generated by Django 5.2.7 on 2026-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_devis_client_email_devis_client_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devis',
            old_name='client_phone',
            new_name='company_bce',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client_email',
        ),
        migrations.AddField(
            model_name='devis',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
