# Generated by Django 5.2.7 on 2026-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_internalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='heure_livraison',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
