# Generated by Django 5.2.7 on 2026-10-06 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_heure_livraison'),
        ('reservations', '0008_remove_reservation_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_set', to='reservations.reservation'),
        ),
    ]
