# Generated by Django 5.2.7 on 2026-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_devis_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
