# Generated by Django 5.2.7 on 2026-05-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_accessory_photobooth_accessory_active_and_more'),
        ('photobooths', '0009_delete_accessory_remove_photobooth_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='price',
        ),
        migrations.AddField(
            model_name='accessory',
            name='photobooth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photobooths.photobooth'),
        ),
    ]
