# Generated by Django 5.2.7 on 2026-08-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_accessory_active_remove_accessory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('fond_ecran', "Fond d'écran"), ('accessoire', 'Accessoire')], default='accessoire', max_length=20),
        ),
    ]
