# Generated by Django 5.2.7 on 2026-10-06 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_promotionbanner_delete_banner'),
        ('photobooths', '0011_photobooth_description_en_photobooth_description_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photobooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photobooths.photobooth')),
            ],
        ),
    ]
